-- Generated by spritter v1.8.0 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 0 },
  ["file_count"] = 1,
  ["height"] = 39,
  ["line_length"] = 5,
  ["lines_per_file"] = 2,
  ["scale"] = 0.5,
  ["shift"] = {-114 / 64, -97.5 / 64},
  ["sprite_count"] = 10,
  ["width"] = 38,
}
