-- Generated by spritter v1.8.0 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 0 },
  ["file_count"] = 1,
  ["height"] = 264,
  ["line_length"] = 10,
  ["lines_per_file"] = 6,
  ["scale"] = 0.5,
  ["shift"] = {-0.5 / 64, 3 / 64},
  ["sprite_count"] = 60,
  ["width"] = 219,
}
