-- Generated by spritter v1.8.0 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 0 },
  ["file_count"] = 1,
  ["height"] = 135,
  ["line_length"] = 5,
  ["lines_per_file"] = 12,
  ["scale"] = 0.5,
  ["shift"] = {-7 / 64, 58.5 / 64},
  ["sprite_count"] = 60,
  ["width"] = 298,
}
